services:
  redis:
    image: redis:7.2-alpine
    container_name: sql-agent-dev-redis
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --save 60 1000
    volumes:
      - redis_data:/data
    # ports:
    #   - "6378:6379"
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      network: host
    container_name: sql-agent-dev-api
    env_file: api/.env
    ports:
      - "8101:8000"
    volumes:
      - ./api:/app
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      network: host
    container_name: sql-agent-dev-frontend
    env_file: frontend/.env
    depends_on:
      - api
    ports:
      - "8102:8501"
    volumes:
      - ./frontend:/app

  # Serviço responsável por executar os testes em api/tests
  api-test:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - api/.env
    volumes:
      - ./api/tests:/app/tests
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - PYTHONWARNINGS=ignore::DeprecationWarning
    command: ["pytest", "tests/", "--cov=/app/src/"]
    profiles:
      - test

volumes:
  redis_data:

networks:
  default:
    name: sql-agent-dev-network
    external: true
    driver: bridge